#pragma once
#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogDroneRPG, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogDroneAI, Log, All);

#define DRONE_DEBUG_ENABLED 0
#define DRONE_EQS_DEBUG_ENABLED DRONE_DEBUG_ENABLED && 1
#define DRONE_AI_DEBUG_ENABLED DRONE_DEBUG_ENABLED && 1